"use client"
import React, { useEffect } from 'react';
import { ThemeProvider } from 'styled-components';
import { Dark, Light } from '@/utils/Variables';
import NavigatioBar from '@/components/NavigationBar';
import { Inter } from 'next/font/google';
import { useThemeToggle } from '@/context/ThemProvider';
import type { Metadata } from 'next'
import '@/styles/globals.css'


export const metadata: Metadata = {
  title: 'Meborny',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { theme } = useThemeToggle();

  return (
    <html lang="en">
      <body style={{margin:'0px'}}>
        <ThemeProvider theme={theme === 'dark' ? { ...Dark } : { ...Light }}>
          <NavigatioBar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}